### ISSUE TITLE
Outcome Always Success?

### ISSUE THREAD

**Issue by skoonin** [8BitJonny/gh-get-current-pr#187]
## Subject of the issue

Clarification on documentation.   I am wondering if I am interpreting it correctly that if the `outcome` of the action is that the commit is NOT part of a PR, it will **not** return `success`? 

In my testing, it is returning `success` regardless of it a PR exists. So using the conditional `if: steps.PR.outcome == 'success'` doesn't really help me in directing things depending on if it is a PR or not. 

I am able to use this how I need it by focusing on the pr number output, however the outcome being successful seems strange to me? 

thanks for creating this! 

## Your git environment
using a self-hosted github runner in github enterprise v3.7 (latest)

## Steps to reproduce
In theory this should work everywhere and not require my environment.  My workflow is below.

## Expected behaviour
If commit is not part of a PR, action will not return success

## Actual behaviour
success is returned regardless.  However the PR information outputs are empty.

Workflow: 
```
name: Workflow

on:
  push:
    branches-ignore:
      - main

# stops current jobs if a new commit is pushed to the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

PR:
    runs-on: [dev, terraform]
    outputs:
      PR_STATUS: ${{ steps.pr-check.outputs.PR_STATUS }}
      PR_NUMBER: ${{ steps.PR.outputs.number }}
      PR_OUTCOME: ${{ steps.PR.outcome }}
    steps:
      - uses: synced-actions/gh-get-current-pr@2.1.3
        id: PR
      - id: pr-check
        run: |
          if [ ${{ steps.PR.outputs.number }} == 0 ]; then
            echo "PR_STATUS=false" >> $GITHUB_OUTPUT
          else
            echo "PR_STATUS=true" >> $GITHUB_OUTPUT
          fi

  test:
    needs: PR
    runs-on: [dev, terraform]
    steps:
      - run: |
          echo "Status:" ${{ needs.PR.outputs.PR_STATUS }} and Number: ${{ needs.PR.outputs.PR_NUMBER }}""
      - if: needs.PR.outputs.PR_STATUS == true
        run: |
          echo "TRUE PR status is ${{ needs.PR.outputs.PR_STATUS }}"
      - if: needs.PR.outputs.PR_STATUS != true
        run: |
          echo "FALSE PR status : ${{ needs.PR.outputs.PR_STATUS }}"
      - if: needs.PR.outputs.PR_NUMBER == 0
        run: |
          echo "empty PR NUMBER : ${{ needs.PR.outputs.PR_NUMBER }}"
      - if: needs.PR.outputs.PR_NUMBER != 0
        run: |
          echo "existing PR NUMBER is ${{ needs.PR.outputs.PR_NUMBER }}"
```
