### ISSUE TITLE
Error reading JToken from JsonReader. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by Mexmorize** [8BitJonny/gh-get-current-pr#195]
## Subject of the issue
Trying to get this action to work although I either get an empty JSON or an error.

## Your git environment
I've added in my action file below
```
name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize', 'reopened']

jobs:
  pr_linter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Lint branch name and PR title
        uses: aschbacd/gitlint-action@v1.1.0
        with:
          commit-message-subject-max-length: 100
          re-commit-message-subject: .*
          re-branch-name: '^[0-9]{4}-'
          re-pull-request-title: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)'

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      
      - name: Running on a pull request branch.
        id: extract_branch
        if: steps.branch-name.outputs.is_default == 'false'
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
          echo "branch_name=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV

      - name: step1
        id: step1
        run: echo 'step_1_json={"a":1}' >> $GITHUB_ENV
        if: true

      - name: step2
        run: echo $A && echo $B && echo $C
        env:
          A: ${{ env.step_1_json && fromJSON(env.step_1_json).a }}
          B: ${{ env.step_1_json }}
          C: ${{ fromJSON(env.step_1_json).a }}
        if: true

      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR
        with:
          sha: ${{ github.event.pull_request.head.sha }}

      - run: echo "PR ${prNumber} ${prTitle} at ${prUrl}"
        if: steps.PR.outcome == 'success'
        env:
          # TODO: try and get JSON object with the full PR object working
          # toJSON(fromJSON(...pr)) parses it into memory and then format is with pretty-print.
          prJSON: ${{ toJSON(fromJSON(steps.current_pr.outputs.pr)) }}
          # Direct access to common PR properties
          prNumber: ${{ steps.PR.outputs.number }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
          prLabel: ${{ steps.PR.outputs.pr_labels }}
        
        
      - if: ${{ steps.PR.outputs.pr_body }} != 'Fixed AB#${{ env.branch_name }}'
        uses: DerekRoberts/action-pr-description-add@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # add_markdown: Fixed AB#${{ env.branch_name }}
```

## Steps to reproduce
Run the action

## Expected behaviour
It does not error and I get a JSON back

## Actual behaviour
I get an error and/or empty JSON returned.

![image](https://user-images.githubusercontent.com/39421227/205717386-211397a5-2556-4950-9438-cdfb35af8037.png)

**Comment by 8BitJonny** [comment]
Two issues here.
First issue is that there is a typo in the step id
```diff
- prJSON: ${{ toJSON(fromJSON(steps.current_pr.outputs.pr)) }}
+ prJSON: ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
```

And the actual error message that you see `The template is not valid` is saying that the JSON string is not valid and therefore fails to be parsed by `fromJSON()`. This is because the Readme is currently incorrect with the if condition.
This issue is partly related to #188 in that we actually have to check two levels of error reporting.
To demonstrate this by example:

`if: steps.PR.outcome == 'success'` only tells us that this github action runs without throwing an error and completely aborting the execution. BUT it is no guarantee that the action actually found a PR. So the full if condition must be 
`if: steps.PR.outcome == 'success' && steps.PR.outputs.pr` because `if steps.PR.outputs.pr` will actually guarantee that a PR has been found.
Because if no PR is found, `steps.PR.outputs.pr` won't be set to a value at all which means that its no valid json string and therefore the error message is shown that you see in your logs

**Comment by 8BitJonny** [comment]
I'll update the readme right now, to actually reflect the proper way of checking the output with the if condition 
`if: steps.PR.outcome == 'success' && steps.PR.outputs.pr`

And then in a few days, I'll also release a new version, to introduce a new output variable being `steps.PR.outputs.pr-found` to have an output that is a.) always set, no matter if pr is found or not and b.) is solely responsible for reporting if the PR is found or not

**Comment by duxbuse** [comment]
@8BitJonny 

I have recently tried to use the example from `Outputs` in the readme and got the same issue.

```yaml
    steps:
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR

      - run: echo "PR ${prNumber} ${prTitle} at ${prUrl} is ${prJSON}"
        if: steps.PR.outputs.pr_found == 'true'
        env:
          # JSON object with the full PR object
          # toJSON(fromJSON(...pr)) parses it into memory and then format is with pretty-print.
          prJSON: ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
          # Direct access to common PR properties
          prNumber: ${{ steps.PR.outputs.number }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
          prLabel: ${{ steps.PR.outputs.pr_labels }}
 ```
 
 gives
 
 ```txt
Error: The template is not valid. .github/workflows/test.yml : Error reading JToken from JsonReader. Path '', line 0, position 0.
 ```
