### ISSUE TITLE
Default branch not working

### ISSUE THREAD

**Issue by antoninlanglade** [8BitJonny/gh-get-current-pr#204]
## Subject of the issue
Default branch not working

## Your git environment
I use it with this configuration. When I try launch an action after deploy it's currently working everywhere execpt on the default branch _(which is development on my project)_

```
on:
  deployment_status:
    branches:
      - development
      - staging
      - main
```

## Steps to reproduce
When you try to use it on a deployment_status github action it's currently not working if you are the default branch

## Expected behaviour
<img width="474" alt="image" src="https://user-images.githubusercontent.com/1774288/207870978-ecdbc8ce-d7df-46ce-8eda-3c14dbc8b1e9.png">

## Actual behaviour
<img width="514" alt="image" src="https://user-images.githubusercontent.com/1774288/207870935-913df925-5abb-4cac-a7f4-06b73909d0ef.png">
