### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by patrickelectric** [8BitJonny/gh-get-current-pr#253]
## Subject of the issue
The action is not working

## Your git environment
I have a step that is like that:
```
      - name: Fetch PR
        if: ${{ github.event.pull_request }}
        uses: 8BitJonny/gh-get-current-pr@2.2.0

      - name: Rebase PR with target
        if: ${{ github.event.pull_request }}
        run: |
          git rebase $GITHUB_BASE_REF
          git log $GITHUB_BASE_REF..HEAD --pretty=format:"%h - %s (%an)"
```
![image](https://user-images.githubusercontent.com/1215497/235300860-bb5c363e-a4ec-4019-b9e3-48264ed7bac6.png)

## Expected behaviour
To fetch the current PR

## Actual behaviour
It's failing

**Comment by roman-parkhunovskyi** [comment]
Confirm. 
In my workflow there are permissions defined as follows:
```
permissions:
  id-token: write
  contents: read
```
then
```
    steps:
      - id: PR
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          # github-token: ${{ secrets.GITHUB_TOKEN }} - didn't work as well
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Neither passing `GITHUB_TOKEN` env nor github-token works, with the same outcome.

**Comment by dargmuesli** [comment]
Are your repositories on which this issue occurs private by any chance?

**Comment by nnamacha** [comment]
where are you supposed to make these changes?

**Comment by dargmuesli** [comment]
```
jobs:
  <job_name>:
    permissions:
      pull-requests: read
```
