### ISSUE TITLE
PR between forks 

### ISSUE THREAD

**Issue by lldelisle** [8BitJonny/gh-get-current-pr#293]
## Subject of the issue
I may be wrong but it seems that the action does not find the corresponding PR when it is a PR across forks.

## Your git environment
* On https://github.com/lldelisle/iwc
* The workflow is:
https://github.com/lldelisle/iwc/blob/36c65a61e9382b63a2e446ebe533e08dbf4253da/.github/workflows/workflow_test.yml#L101-L110
```
    - name: Get PR object
      if: failure()
      uses: 8BitJonny/gh-get-current-pr@2.2.0
      id: failed_pr_number
      with:
        sha: ${{ github.event.pull_request.head.sha }}
    - name: Debug GetPR output
      if: failure()
      run: |
          echo ${{ steps.failed_pr_number.outputs.number }}
```
* PR from myself gave the correct PR number:
PR: https://github.com/lldelisle/iwc/pull/5
Action: https://github.com/lldelisle/iwc/actions/runs/6890547992/job/18744182033#step:10:13
* PR from another fork gave nothing:
PR: https://github.com/lldelisle/iwc/pull/6
Action: https://github.com/lldelisle/iwc/actions/runs/6890942348/job/18745393967?pr=6#step:10:13

## Steps to reproduce
I guess just make a PR between forks should make it reproducible.

## Expected behaviour
I was expecting to find the good PR number

## Actual behaviour
Tell us what happens instead
