### ISSUE TITLE
ability to fetch data from PR_URL (when triggered by a comment)

### ISSUE THREAD

**Issue by digitalkaoz** [8BitJonny/gh-get-current-pr#318]
## Subject of the issue
i want to get detailed infos about a PR when triggered by issue_comment (have a PR_URL, but nothing else)

## Your git environment

```yaml
on:
  issue_comment:
    types: [created, edited]
...
  steps:
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR
        with:
          prUrl: ${{ github.event.issue.html_url }} #thats what i need
```

## Expected behaviour
Works the same as with a concrete SHA

## Actual behaviour
doesnt work at all
